import { cn } from "../lib/utils";

export const proseStyle = (size: "sm" | "base" = "sm", className?: string) =>
  cn(
    "prose prose-custom prose-sm focus:outline-none",
    "font-sans text-[14px] leading-[1.9]",
    "[&_p]:text-[14px] [&_p]:leading-[1.9] [&_p]:mb-8 [&_p]:text-foreground/85",
    "[&_h1]:text-[1.75em] [&_h1]:font-bold [&_h1]:mt-12 [&_h1]:mb-5 [&_h1]:leading-tight [&_h1]:text-foreground",
    "[&_h2]:text-[1.5em] [&_h2]:font-bold [&_h2]:mt-10 [&_h2]:mb-5 [&_h2]:leading-tight [&_h2]:text-foreground",
    "[&_h3]:text-[1.2em] [&_h3]:font-semibold [&_h3]:mt-8 [&_h3]:mb-4 [&_h3]:text-foreground",
    "[&_h4]:text-[1.1em] [&_h4]:font-semibold [&_h4]:mt-6 [&_h4]:mb-3 [&_h4]:text-foreground",
    "[&_h5]:text-[1em] [&_h5]:font-medium [&_h5]:mt-5 [&_h5]:mb-2 [&_h5]:text-foreground",
    "[&_h6]:text-[0.95em] [&_h6]:font-medium [&_h6]:mt-4 [&_h6]:mb-2 [&_h6]:text-foreground/90",
    "[&_ul]:mb-5 [&_ul]:pl-5 [&_ul]:list-disc [&_ul]:space-y-1.5",
    "[&_ol]:mb-5 [&_ol]:pl-5 [&_ol]:list-decimal [&_ol]:space-y-1.5",
    "[&_li]:leading-[1.8] [&_li]:text-foreground/85",
    "[&_code]:bg-amber-500/10 [&_code]:text-amber-700 dark:[&_code]:text-amber-400 [&_code]:font-mono [&_code]:rounded [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-[0.9em] [&_code]:font-medium",
    "[&_pre]:bg-zinc-900 [&_pre]:text-zinc-100 [&_pre]:font-mono [&_pre]:rounded-xl [&_pre]:px-5 [&_pre]:py-4 [&_pre]:my-6 [&_pre]:text-[0.85em] [&_pre]:overflow-x-auto [&_pre]:border [&_pre]:border-zinc-800",
    "[&_pre_code]:bg-transparent [&_pre_code]:text-inherit [&_pre_code]:p-0 [&_pre_code]:text-[1em] [&_pre_code]:font-normal",
    "[&_a]:text-accent [&_a]:underline [&_a]:underline-offset-2 [&_a]:decoration-accent/40 hover:[&_a]:decoration-accent [&_a]:font-normal",
    "[&_strong]:font-semibold [&_strong]:text-foreground",
    "[&_em]:italic",
    "[&_blockquote]:border-l-0 [&_blockquote]:pl-5 [&_blockquote]:italic [&_blockquote]:text-foreground/70 [&_blockquote]:my-6",
    "[&_hr]:my-8 [&_hr]:border-foreground/10",
    "[&_mark]:bg-yellow-300/40 [&_mark]:text-yellow-900 dark:[&_mark]:bg-yellow-500/30 dark:[&_mark]:text-yellow-200 [&_mark]:rounded [&_mark]:px-1 [&_mark]:py-0.5 [&_mark]:-mx-0.5",
    {
      sm: "",
      base: "[&_p]:text-[16px]",
    },
    className
  );

export const proseStyleVibrancy = (size: "sm" | "base" = "sm", className?: string) =>
  cn(
    "prose prose-vibrancy prose-sm focus:outline-none",
    "font-sans text-[14px] leading-[1.9]",
    "[&_p]:text-[14px] [&_p]:leading-[1.9] [&_p]:mb-8 [&_p]:text-foreground/85",
    "[&_h1]:text-[1.75em] [&_h1]:font-bold [&_h1]:mt-12 [&_h1]:mb-5 [&_h1]:leading-tight [&_h1]:text-foreground/90",
    "[&_h2]:text-[1.5em] [&_h2]:font-bold [&_h2]:mt-10 [&_h2]:mb-5 [&_h2]:leading-tight [&_h2]:text-foreground/90",
    "[&_h3]:text-[1.2em] [&_h3]:font-semibold [&_h3]:mt-8 [&_h3]:mb-4 [&_h3]:text-foreground/90",
    "[&_h4]:text-[1.1em] [&_h4]:font-semibold [&_h4]:mt-6 [&_h4]:mb-3 [&_h4]:text-foreground/90",
    "[&_h5]:text-[1em] [&_h5]:font-medium [&_h5]:mt-5 [&_h5]:mb-2 [&_h5]:text-foreground/90",
    "[&_h6]:text-[0.95em] [&_h6]:font-medium [&_h6]:mt-4 [&_h6]:mb-2 [&_h6]:text-foreground/85",
    "[&_ul]:mb-5 [&_ul]:pl-5 [&_ul]:list-disc [&_ul]:space-y-1.5 [&_ul]:text-foreground/85",
    "[&_ol]:mb-5 [&_ol]:pl-5 [&_ol]:list-decimal [&_ol]:space-y-1.5 [&_ol]:text-foreground/85",
    "[&_li]:leading-[1.8] [&_li]:text-foreground/85",
    "[&_code]:bg-amber-500/10 [&_code]:text-amber-700 dark:[&_code]:text-amber-400 [&_code]:font-mono [&_code]:rounded [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:text-[0.9em] [&_code]:font-medium",
    "[&_pre]:bg-zinc-900 [&_pre]:text-zinc-100 [&_pre]:font-mono [&_pre]:rounded-xl [&_pre]:px-5 [&_pre]:py-4 [&_pre]:my-6 [&_pre]:text-[0.85em] [&_pre]:overflow-x-auto [&_pre]:border [&_pre]:border-zinc-800",
    "[&_pre_code]:bg-transparent [&_pre_code]:text-inherit [&_pre_code]:p-0 [&_pre_code]:text-[1em] [&_pre_code]:font-normal",
    "[&_a]:text-accent [&_a]:underline [&_a]:underline-offset-2 [&_a]:decoration-accent/40 hover:[&_a]:decoration-accent [&_a]:font-normal",
    "[&_strong]:font-semibold [&_strong]:text-foreground/90",
    "[&_em]:italic [&_em]:text-foreground/85",
    "[&_blockquote]:border-l-0 [&_blockquote]:pl-5 [&_blockquote]:italic [&_blockquote]:text-foreground/70 [&_blockquote]:my-6",
    "[&_hr]:my-8 [&_hr]:border-foreground/10",
    "[&_mark]:bg-yellow-300/40 [&_mark]:text-yellow-900 dark:[&_mark]:bg-yellow-500/30 dark:[&_mark]:text-yellow-200 [&_mark]:rounded [&_mark]:px-1 [&_mark]:py-0.5 [&_mark]:-mx-0.5",
    {
      sm: "",
      base: "[&_p]:text-[16px]",
    },
    className
  );

export const proseSmallStyle = (className?: string) =>
  cn(
    "prose prose-custom prose-sm focus:outline-none",
    "font-sans text-[14px] leading-[1.45rem] tracking-[-0.005em] font-[450]",
    "[&_p]:text-[14px] [&_p]:leading-[1.45rem] [&_p]:tracking-[-0.005em] [&_p]:font-[450] [&_p]:text-foreground/80",
    "[&_p+p]:mt-3",
    "[&_header]:flex [&_header]:flex-col [&_header]:gap-1 [&_header]:pb-3",
    "[&_h1]:text-[18px] [&_h1]:font-[580] [&_h1]:tracking-[-0.02em] [&_h1]:leading-[1.4] [&_h1]:text-foreground/85 [&_h1]:mb-1 [&_h1]:mt-0",
    "[&_.tagline]:text-[14px] [&_.tagline]:font-[450] [&_.tagline]:text-foreground/50",
    "[&_h2]:text-[13px] [&_h2]:font-[550] [&_h2]:tracking-[-0.005em] [&_h2]:text-foreground/78 [&_h2]:mb-[1.125rem] [&_h2]:mt-8 [&_h2]:flex [&_h2]:items-center [&_h2]:gap-3",
    "[&_h2]:after:content-[''] [&_h2]:after:flex-1 [&_h2]:after:h-px [&_h2]:after:bg-foreground/8",
    "[&_h3]:text-[13px] [&_h3]:font-medium [&_h3]:tracking-[-0.005em] [&_h3]:text-foreground/70 [&_h3]:mt-6 [&_h3]:mb-[0.375rem]",
    "[&_h3:first-child]:mt-2",
    "[&_section]:mt-6",
    "[&_section+section]:mt-10",
    "[&_ul]:pl-4 [&_ul]:flex [&_ul]:flex-col [&_ul]:gap-1",
    "[&_ol]:pl-4 [&_ol]:flex [&_ol]:flex-col [&_ol]:gap-1",
    "[&_li]:text-[14px] [&_li]:font-[450] [&_li]:leading-[1.45rem] [&_li]:tracking-[-0.005em] [&_li]:text-foreground/80",
    "[&_li_strong]:font-[550]",
    "[&_li::marker]:text-foreground/25",
    "[&_ul_ul]:mt-1 [&_ul_ul]:gap-0.5",
    "[&_ul_ul_li]:text-[13px] [&_ul_ul_li]:text-foreground/60",
    "[&_p+ul]:mt-2 [&_p+ol]:mt-2",
    "[&_ul+p]:mt-3 [&_ol+p]:mt-3",
    "[&_code]:text-[13px] [&_code]:bg-foreground/4 [&_code]:px-[0.35rem] [&_code]:py-[0.1rem] [&_code]:rounded [&_code]:text-foreground/75 [&_code]:font-mono",
    "[&_pre]:text-[12px] [&_pre]:leading-[1.55] [&_pre]:bg-[#f8f8f8] [&_pre]:text-[#333] [&_pre]:font-mono [&_pre]:rounded-lg [&_pre]:px-4 [&_pre]:py-[0.875rem] [&_pre]:my-[0.625rem] [&_pre]:border [&_pre]:border-foreground/6 [&_pre]:overflow-x-auto [&_pre]:whitespace-pre-wrap [&_pre]:break-words",
    "[&_pre_code]:bg-transparent [&_pre_code]:text-inherit [&_pre_code]:p-0 [&_pre_code]:text-[1em]",
    "[&_a]:text-[#2480ed] [&_a]:no-underline hover:[&_a]:text-[#74b1fd] [&_a]:transition-colors [&_a]:duration-200",
    "[&_strong]:font-[550] [&_strong]:text-foreground",
    "[&_em]:italic",
    "[&_blockquote]:border-l-2 [&_blockquote]:border-[#e0e0e0] [&_blockquote]:pl-4 [&_blockquote]:my-2 [&_blockquote]:text-foreground/60 [&_blockquote]:italic",
    "[&_table]:w-full [&_table]:text-[13px] [&_table]:my-4 [&_table]:border-collapse",
    "[&_th]:text-left [&_th]:font-[550] [&_th]:text-foreground/70 [&_th]:pb-2 [&_th]:pr-4 [&_th]:border-b [&_th]:border-foreground/10",
    "[&_td]:py-2 [&_td]:pr-4 [&_td]:text-foreground/70 [&_td]:border-b [&_td]:border-foreground/6 [&_td]:align-top",
    "[&_tr:last-child_td]:border-b-0",
    className
  );
