export const IPC = {
  AGENT_START: "agent:start",
  AGENT_STOP: "agent:stop",
  AGENT_STATUS: "agent:status",
  AGENT_GET_MODELS: "agent:get-models",
  AGENT_GENERATE_THREAD_TITLE: "agent:generate-thread-title",
  AGENT_GENERATE_COMMIT_MESSAGE: "agent:generate-commit-message",
  AGENT_MESSAGE: "agent:message",
  AGENT_RESULT: "agent:result",
  AGENT_ERROR: "agent:error",
  AGENT_SDK_SESSION_ID: "agent:sdk-session-id",
  AGENT_TOOL_APPROVAL_REQUEST: "agent:tool-approval-request",
  AGENT_TOOL_APPROVAL_RESPONSE: "agent:tool-approval-response",

  WORKSPACE_LIST: "workspace:list",
  WORKSPACE_CREATE: "workspace:create",
  WORKSPACE_DELETE: "workspace:delete",
  WORKSPACE_SELECT: "workspace:select",
  WORKSPACE_GIT_REFRESH: "workspace:git-refresh",
  WORKSPACE_GIT_BRANCHES: "workspace:git-branches",
  WORKSPACE_GIT_SWITCH_BRANCH: "workspace:git-switch-branch",
  WORKSPACE_GIT_CREATE_BRANCH: "workspace:git-create-branch",
  WORKSPACE_GIT_INIT: "workspace:git-init",
  WORKSPACE_GIT_UNSTAGED_CHANGES: "workspace:git-unstaged-changes",
  WORKSPACE_GET_FILE_DIFF: "workspace:get-file-diff",
  WORKSPACE_REVERT_FILE_CHANGE: "workspace:revert-file-change",
  WORKSPACE_GIT_STAGED_CHANGES: "workspace:git-staged-changes",
  WORKSPACE_GIT_STAGE_FILE: "workspace:git-stage-file",
  WORKSPACE_GIT_UNSTAGE_FILE: "workspace:git-unstage-file",
  WORKSPACE_GIT_COMMIT: "workspace:git-commit",
  WORKSPACE_GIT_PUSH: "workspace:git-push",
  WORKSPACE_GIT_AHEAD_COUNT: "workspace:git-ahead-count",
  WORKSPACE_FILES_CHANGED: "workspace:files-changed",
  WORKSPACE_GIT_CHANGED: "workspace:git-changed",

  DIALOG_SELECT_FOLDER: "dialog:select-folder",

  PROJECT_CREATE_EMPTY: "project:create-empty",
  PROJECT_CLONE: "project:clone",

  READ_DIRECTORY_TREE: "filesystem:read-directory-tree",
  READ_DIRECTORY_CHILDREN: "filesystem:read-directory-children",
  READ_FILE: "filesystem:read-file",

  CHAT_LOAD: "chat:load",
  CHAT_SAVE: "chat:save",
  CHAT_DELETE_THREAD: "chat:delete-thread",
  CHAT_UPDATE_MESSAGE: "chat:update-message",

  CONFIG_GET_ACTIVE_WORKSPACE: "config:get-active-workspace",
  CONFIG_SET_ACTIVE_WORKSPACE: "config:set-active-workspace",

  TERMINAL_CREATE: "terminal:create",
  TERMINAL_WRITE: "terminal:write",
  TERMINAL_RESIZE: "terminal:resize",
  TERMINAL_DESTROY: "terminal:destroy",
  TERMINAL_DATA: "terminal:data",

  API_KEY_GET: "api-key:get",
  API_KEY_SET: "api-key:set",
  API_KEY_HAS: "api-key:has",
  CODEX_API_KEY_GET: "codex-api-key:get",
  CODEX_API_KEY_SET: "codex-api-key:set",
  CODEX_API_KEY_HAS: "codex-api-key:has",
  MINIMAX_API_KEY_GET: "minimax-api-key:get",
  MINIMAX_API_KEY_SET: "minimax-api-key:set",
  MINIMAX_API_KEY_HAS: "minimax-api-key:has",
  API_KEYS_GET: "api-keys:get",
  API_KEYS_SET: "api-keys:set",
  API_KEYS_HAS: "api-keys:has",
  SETTINGS_GET: "settings:get",
  SETTINGS_SET: "settings:set",
  SETTINGS_VALIDATE_MCP_SERVERS: "settings:validate-mcp-servers",
  AUTH_STATUS: "auth:status",
  AUTH_SET_METHOD: "auth:set-method",
  AUTH_LOGIN: "auth:login",

  APP_READY: "app:ready",
  APP_QUIT: "app:quit",
  AGENT_LOG_GET_PATH: "agent-log:get-path",
  AGENT_LOG_READ: "agent-log:read",
  AGENT_LOG_OPEN_FOLDER: "agent-log:open-folder",
  EDITOR_OPEN_FILE: "editor:open-file",

  SKILLS_LIST: "skills:list",
  SKILLS_GET_CONTENT: "skills:get-content",

  CHECKPOINT_CREATE: "checkpoint:create",
  CHECKPOINT_RESTORE: "checkpoint:restore",
  CHECKPOINT_FINALIZE: "checkpoint:finalize",
  CHECKPOINT_SAVE_SNAPSHOTS: "checkpoint:save-snapshots",
  CHECKPOINT_RESTORE_SNAPSHOTS: "checkpoint:restore-snapshots",
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
